Algoritmo "10-tinta"
// Disciplina : [Linguagem e Lógica de Programação] 
// Professor : Thiago Menezes 

Var
l, a, t, m: real


Inicio
escreval("Digite a altura da parede: ")
leia(a)

escreval("Digite a altura da parede: ")
leia(l)

m := l*a

escreval("Sua parede tem ",m:2:2," metros quadrados")
escreval("")
t := m/2

escreval("Você vai precisar de",t," litros de tinta")
Fimalgoritmo