Algoritmo "46-soma6-100"
// Disciplina : [Linguagem e Lógica de Programação]
// Professor : Thiago Menezes
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/03/2024
Var
// Seção de Declarações das variáveis
i,r: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
i := 6
r := 2
enquanto i <= 100 faca
r := r + i
i := i + 2
fimenquanto

escreval(r)
Fimalgoritmo