Algoritmo "48-soma7"
// Disciplina : [Linguagem e Lógica de Programação]
// Professor : Thiago Menezes

Var

   n, i, total : inteiro

Inicio
      para i de 1 ate 7 faca
      escreval("Digite 7 valores e veja a somatoria deles")
      escreval
      escreval("Digite o valor de um numero")
      leia(n)
      limpatela

      total := n + total

      fimpara

      escreval("A somatoria de todos os numeros digitados e de",total)
Fimalgoritmo