Algoritmo "87"
// Disciplina : [Linguagem e Lógica de Programação]
// Professor : Thiago Menezes


var

Procedimento gerador(frase : caracter)
var
   i: inteiro

Inicio
   escreval("--------=================----------")

      escreval("        ",frase)

   escreval("--------=================----------")
fimprocedimento

inicio

   gerador("Aprendendo portugal")


Fimalgoritmo