Algoritmo "88-gerador-04"
// Disciplina : [Linguagem e Lógica de Programação]
// Professor : Thiago Menezes


var

Procedimento gerador(frase : caracter; quan : inteiro)
var
   i: inteiro

Inicio
   escreval("--------=================----------")
   para i := 1 ate quan faca
      escreval(frase)
   fimpara
   escreval("--------=================----------")
fimprocedimento

inicio

   gerador("Aprendendo portugal", 4)


Fimalgoritmo