Algoritmo "funcao01"
// Disciplina : [Linguagem e Lógica de Programação]
// Professor : Thiago Menezes 

Var

n1, n2, m: real
funcao media(a, b: real): real
Inicio
      retorne (a + b) / 2
fimfuncao

inicio

escreva("Digite a 1ª nota do aluno: ")
leia(n1)
escreva("Digite a 2ª nota do aluno: ")
leia(n2)

m := media (n1,n2)

escreval

escreva ("A média das notas do aluno foi ", m:2:1)
escreval


Fimalgoritmo